name: build
on: push

permissions:
  contents: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /bun-next-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: swtup bun
        uses: oven-sh/setup-bun@v1
      - name: Install packages
        run: bun install
      - name: Build
        run: bun run build
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: out
